# -*- coding: utf-8 -*-
from django.test.client import Client as DjangoClient
from django_any.contrib.auth import any_user
from django_any import xunit


class Client(DjangoClient):
    def login_as(self, **kwargs):
        password = xunit.any_string()
        user = any_user(password=password, **kwargs)
        
        if self.login(username=user.username, password=password):
            return user
        raise AssertionError('Can''t login with autogenerated user')

